name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: check has_seen()
      id: check-has_seen
      uses: education/autograding-python-grader@v1
      with:
        timeout: 11
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        CHECK-HAS_SEEN_RESULTS: "${{steps.check-has_seen.outputs.result}}"
      with:
        runners: check-has_seen
